### ISSUE TITLE
这个支持V3算法吗？

### ISSUE THREAD

**Issue by BlingRbt** [updateing/mentohust-proxy#1]
这个支持V3算法吗？

**Comment by BlingRbt** [comment]
Sorry 我没有看清楚 这个是电脑端的....

**Comment by updateing** [comment]
看介绍的话，这个是运行在网关设备上的……

**Comment by BlingRbt** [comment]
哦哦支持OpenWRT啊
是不是需要交叉编译？
这个版本支持V3嘛？

**Comment by updateing** [comment]
既然是代理的话，当然要运行在校园网与内网的桥梁上啊……
1. 给OpenWrt使用的话需要交叉编译
2. 这个版本并没有在认证算法上做任何改动（也就是说与原本MentoHUST相同，只支持v2）因为重点是代理而不是认证

**Comment by BlingRbt** [comment]
谢谢大大
我主要是需要V3的 认证 可惜本人不才 不会反编译V3源码....也看不大懂代码...
哦哦 那这个就相当于一个桥梁 由电脑端进行认证 认证后可以一直在线？不需要电脑了吗？

**Comment by updateing** [comment]
是的，认证后电脑可以关了（希望学校不要对心跳包有太强的验证。在我这里，认证需要v3，但心跳不需要）

关于认证的话，建议你看看支持v4算法的 https://github.com/hyrathb/mentohust 。我这里也有同时支持代理和v4的版本：https://github.com/updateing/mentohust-v4-proxy ，这样（希望）能够解决一切版本了……

**Comment by BlingRbt** [comment]
Wow！Nice Developer！
谢谢！

我刚看到介绍最后说

> “当认证成功后，上游服务器发来EAP-Request-Identity、MD5 Challenge或Failure时，MentoHUST将重新开始监听局域网，并把这些包修改目标MAC地址后转发到局域网，客户端可自行处理。”

是不是说明 当上游需要重新认证时 还是需要电脑端的重新认证？ 
另：V4算法支持V3嘛？

**Comment by updateing** [comment]
是需要电脑重新认证的。但我这边在认证成功后就不会再收到无来由的重新认证的要求，只会有事件触发的Failure（比如被挤掉线或者定时断网）所以还算是能用……

V4据说实际上也是V3的某个变种，你可以看看第一个V4项目的issues，里面有关于学校适配方法的讨论，也许能应用在你的学校。（也就是说这个算法仍应该叫做V3）

**Comment by BlingRbt** [comment]
谢谢~
明白啦 我去研究一下 谢谢大大指点！
